---
- name: Install arch
  hosts: install
  tags: install
  pre_tasks:
    - name: Check boot mode
      ansible.builtin.stat:
        path: "/sys/firmware/efi/fw_platform_size"
      register: efi_size
    - name: Set boot mode fact
      ansible.builtin.set_fact:
        boot_mode: "{{ efi_size.stat.exists | ternary('uefi', 'bios') }}"
  roles:
    - partitions
    - system
    - chroot

- name: Reboot into new installation
  hosts: install
  tags: reboot
  tasks:
    - name: Reboot system
      ansible.builtin.command:
        cmd: "reboot"
      changed_when: false
      async: 1
      poll: 0
    - name: Wait for reboot
      ansible.builtin.wait_for_connection:
        connect_timeout: 20
        timeout: 300
        delay: 5
        sleep: 5

- name: Post installation steps
  tags: post-install
  hosts: configure
  roles:
    - common
    - packages
    - dotfiles
    - cleanup
