---
- name: "Add ArcoLinux Keyring and Mirrorlist"
  loop:
    - "arcolinux-keyring-20251209-3-any.pkg.tar.zst"
    - "arcolinux-mirrorlist-git-24.03-12-any.pkg.tar.zst"
  ansible.builtin.get_url:
    url: "https://github.com/arcolinux/arcolinux_repo/raw/main/x86_64/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: "0755"

- name: "Install Keyring and Mirrorlist"
  loop:
    - "arcolinux-keyring-20251209-3-any.pkg.tar.zst"
    - "arcolinux-mirrorlist-git-24.03-12-any.pkg.tar.zst"
  community.general.pacman:
    name: "/tmp/{{ item }}"

- name: "Add ArcoLinux Repos to /etc/pacman.conf"
  block:
    - name: "Append Repos to /etc/pacman.conf"
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        marker: ""
        insertbefore: EOF
        block: |
          #[arcolinux_repo_testing]
          #SigLevel = PackageRequired DatabaseNever
          #Include = /etc/pacman.d/arcolinux-mirrorlist

          [arcolinux_repo]
          SigLevel = PackageRequired DatabaseNever
          Include = /etc/pacman.d/arcolinux-mirrorlist

          [arcolinux_repo_3party]
          SigLevel = PackageRequired DatabaseNever
          Include = /etc/pacman.d/arcolinux-mirrorlist

          [arcolinux_repo_xlarge]
          SigLevel = PackageRequired DatabaseNever
          Include = /etc/pacman.d/arcolinux-mirrorlist

    - name: Update Pacman Database
      community.general.pacman:
        update_cache: true
