---
- name: Check Adw-gtk3 Theme
  ansible.builtin.stat:
    path: "/usr/share/themes/adw-gtk3"
  register: adw_gtk3

- name: Install adw-gtk3 theme
  when: not adw_gtk3.stat.exists
  community.general.pacman:
    state: present
    package: adw-gtk-theme
