---
- name: Create pictures directory
  ansible.builtin.file:
    state: directory
    path: "/home/{{ main_user }}/Pictures"
    owner: "{{ main_user }}"
    mode: "755"

- name: Copy wallpaper
  ansible.builtin.copy:
    src: "wall.png"
    dest: "/home/{{ main_user }}/Pictures/wall.png"
    owner: "{{ main_user }}"
    mode: "644"
