---
- name: Remove ansible networkmanager profile
  ansible.builtin.file:
    path: "/etc/NetworkManager/system-connections/ansible-static.nmconnection"
    state: absent

- name: Reset SSH root login configuration
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "#PermitRootLogin yes"
