---
- name: Create Main Partition
  community.general.parted:
    device: "{{ install_disk }}"
    label: gpt
    number: 2
    state: present
    part_start: 304MiB
    fs_type: btrfs

- name: Create Btrfs Partition
  community.general.filesystem:
    dev: "{{ install_disk }}2"
    fstype: btrfs

- name: Create btrfs subvolumes
  community.general.btrfs_subvolume:
    automount: true
    filesystem_device: "{{ install_disk }}2"
    name: "/{{ item }}"
    state: present
  loop:
    - "@"
    - "@home"
    - "@snapshots"
