---
- name: Create system boot partiton(s)
  ansible.builtin.include_tasks:
    file: "{{ boot_mode }}.yml"

- name: Create swap
  when: swap_size_mib > 0
  ansible.builtin.include_tasks:
    file: "swap.yml"

- name: Create main partition(s)
  ansible.builtin.include_tasks:
    file: "{{ filesystem }}.yml"

- name: Mount partition(s)
  ansible.builtin.include_tasks:
    file: "mount-{{ filesystem }}.yml"
