---
- name: Mount Root Subvolume
  ansible.posix.mount:
    path: "{{ fsroot }}"
    src: "{{ install_disk }}{{ (swap_size_mib > 0) | ternary(3, 2) }}"
    fstype: btrfs
    opts: "{{ btrfs_mount_opts }},subvol=/@"
    state: mounted

- name: Create FS Structure
  ansible.builtin.file:
    path: "{{ fsroot }}/{{ item }}"
    state: directory
    mode: "755"
  loop:
    - "efi"
    - "home"
    - ".snapshots"

- name: Mount System Boot Partition(s)
  when: boot_mode == "uefi"
  ansible.posix.mount:
    path: "{{ fsroot }}/efi"
    src: "{{ install_disk }}1"
    fstype: "vfat"
    opts: defaults
    state: mounted

- name: Mount Other Subvolumes
  ansible.posix.mount:
    path: "{{ fsroot }}/{{ item['dir'] }}"
    src: "{{ install_disk }}{{ (swap_size_mib > 0) | ternary(3, 2) }}"
    fstype: btrfs
    opts: "{{ btrfs_mount_opts }},subvol={{ item['subvol'] }}"
    state: mounted
  loop:
    - dir: "home"
      subvol: "/@home"
    - dir: ".snapshots"
      subvol: "/@snapshots"
