---
- name: Ensure flatpak is present
  community.general.pacman:
    state: present
    package:
      - flatpak

- name: Add flathub remote repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: Install flatpak apps
  loop: "{{ apps }}"
  community.general.flatpak:
    state: present
    name: "{{ item }}"
