---
arcolinux_repos: false
chaotic_repos: false
desktop: none
cli_tools: true
fonts: false
nvidia: false
docker: false
bluetooth: false
extras: false
virtualization: false
java: false
rust: false
office: false
