---
- name: Generate Fstab File
  ansible.builtin.shell:
    cmd: "genfstab -U {{ fsroot }} > {{ fsroot }}/etc/fstab"

- name: Sync Hardware Clock with System Clock
  ansible.builtin.command:
    cmd: "arch-chroot {{ fsroot }} /usr/bin/hwclock --systohc"
  changed_when: false

- name: Set Locale
  ansible.builtin.lineinfile:
    path: "{{ fsroot }}/etc/locale.gen"
    regexp: '^#(en_US\.UTF-8 UTF-8)'
    line: '\g<1>'
    backrefs: true

- name: Generate Locales
  ansible.builtin.command:
    cmd: "arch-chroot {{ fsroot }} /usr/bin/locale-gen"
  changed_when: true

- name: Set Locale Config File
  ansible.builtin.copy:
    content: "LANG=en_US.UTF-8"
    dest: "{{ fsroot }}/etc/locale.conf"
    mode: "644"

- name: Set Hostname
  ansible.builtin.copy:
    content: "{{ hostname }}"
    dest: "{{ fsroot }}/etc/hostname"
    mode: "644"

- name: Allow Wheel Group to Run Sudo
  ansible.builtin.lineinfile:
    path: "{{ fsroot }}/etc/sudoers"
    regexp: '^#%wheel ALL=\(ALL:ALL\) ALL'
    line: "%wheel ALL=(ALL:ALL) ALL"

- name: Install GRUB2
  block:
    - name: "Install GRUB2 (UEFI)"
      when: boot_mode == 'uefi'
      ansible.builtin.command:
        cmd: "arch-chroot {{ fsroot }} /usr/bin/grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB"
      changed_when: true

    - name: "Install GRUB2 (BIOS)"
      when: boot_mode == 'bios'
      ansible.builtin.command:
        cmd: "arch-chroot {{ fsroot }} /usr/bin/grub-install {{ install_disk }}"
      changed_when: true

    - name: "Generate GRUB2 Configuration"
      changed_when: true
      ansible.builtin.command:
        cmd: "arch-chroot {{ fsroot }} /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg"

- name: Enable Services
  changed_when: true
  ansible.builtin.command:
    cmd: "arch-chroot {{ fsroot }} /usr/bin/systemctl enable {{ item }}.service"
  loop:
    - "sshd"
    - "NetworkManager"

- name: Set Root Password
  changed_when: true
  ansible.builtin.command:
    cmd: "arch-chroot {{ fsroot }} /usr/bin/bash -c 'echo 'root:{{ ansible_password }}' | chpasswd'"

- name: Permit Root SSH Login Temporarily
  ansible.builtin.lineinfile:
    path: "{{ fsroot }}/etc/ssh/sshd_config"
    regexp: "^#PermitRootLogin"
    line: "PermitRootLogin yes"

- name: Setup NetworkManager Profile
  ansible.builtin.include_tasks:
    file: "network.yml"
