---
- name: Set networkmanager profile for the current IP
  ansible.builtin.template:
    src: "ansible-static.nmconnection.j2"
    dest: "{{ fsroot }}/etc/NetworkManager/system-connections/ansible-static.nmconnection"
    mode: "600"
